"""
ATLAS Database Models
SQLAlchemy models for the AI Trading, Logic & Analysis System.

All tables prefixed with 'atlas_' to avoid conflicts with VALIS tables.
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, Date,
    Text, JSON, ForeignKey, Index, UniqueConstraint, Enum
)
from sqlalchemy.orm import declarative_base, relationship
import enum

Base = declarative_base()


class SignalDirection(enum.Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class ChangeType(enum.Enum):
    NEW = "NEW"
    INCREASED = "INCREASED"
    DECREASED = "DECREASED"
    CLOSED = "CLOSED"
    UNCHANGED = "UNCHANGED"


class ThesisStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    INVALIDATED = "INVALIDATED"
    CLOSED_WIN = "CLOSED_WIN"
    CLOSED_LOSS = "CLOSED_LOSS"
    PAUSED = "PAUSED"


class TradeDirection(enum.Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class AtlasCompany(Base):
    """
    Companies in the ATLAS universe.
    Core reference table for all company-related data.
    """
    __tablename__ = "atlas_companies"
    
    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=True, nullable=False, index=True)
    cik = Column(String(10), index=True)  # SEC CIK number
    name = Column(String(255))
    sector = Column(String(100), index=True)
    industry = Column(String(100))
    market_cap = Column(Float)  # Latest market cap in USD
    in_universe = Column(Boolean, default=True)  # Active in trading universe
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    filings = relationship("AtlasFiling", back_populates="company")
    briefs = relationship("AtlasDeskBrief", back_populates="company")
    theses = relationship("AtlasThesis", back_populates="company")
    
    def __repr__(self):
        return f"<AtlasCompany(ticker='{self.ticker}', name='{self.name}')>"


class AtlasFiling(Base):
    """
    SEC filings (10-K, 10-Q, 8-K, etc.) downloaded and processed.
    """
    __tablename__ = "atlas_filings"
    
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("atlas_companies.id"), nullable=False, index=True)
    
    filing_type = Column(String(20), nullable=False)  # 10-K, 10-Q, 8-K, etc.
    accession_number = Column(String(25), unique=True)  # SEC accession number
    filed_date = Column(Date, nullable=False, index=True)
    period_end_date = Column(Date)  # Fiscal period ending
    
    # Storage
    raw_text_path = Column(String(500))  # Path to downloaded text file
    extracted_json = Column(JSON)  # Parsed XBRL financials
    
    # Processing status
    processed = Column(Boolean, default=False)
    processed_at = Column(DateTime)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    company = relationship("AtlasCompany", back_populates="filings")
    
    __table_args__ = (
        Index("ix_atlas_filings_company_date", "company_id", "filed_date"),
    )
    
    def __repr__(self):
        return f"<AtlasFiling(company_id={self.company_id}, type='{self.filing_type}', date='{self.filed_date}')>"


class AtlasDeskBrief(Base):
    """
    Analysis briefs generated by sector desk agents.
    Each brief is a structured JSON analysis of a company.
    """
    __tablename__ = "atlas_desk_briefs"
    
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("atlas_companies.id"), nullable=False, index=True)
    
    desk_name = Column(String(50), nullable=False, index=True)  # Semiconductor, Biotech, etc.
    analysis_date = Column(Date, nullable=False, index=True)
    
    # Analysis output
    brief_json = Column(JSON, nullable=False)  # Full structured brief
    signal_direction = Column(String(20))  # BULLISH, BEARISH, NEUTRAL
    confidence = Column(Float)  # 0.0 to 1.0
    
    # Source filing
    filing_id = Column(Integer, ForeignKey("atlas_filings.id"))
    filing_type = Column(String(20))
    filing_date = Column(Date)
    
    # Key extracts for quick access
    cio_briefing = Column(Text)  # 50-word summary
    bull_case = Column(Text)
    bear_case = Column(Text)
    
    # Metadata
    model_used = Column(String(100))  # Claude model version
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    company = relationship("AtlasCompany", back_populates="briefs")
    
    __table_args__ = (
        Index("ix_atlas_briefs_desk_date", "desk_name", "analysis_date"),
        UniqueConstraint("company_id", "desk_name", "analysis_date", name="uq_brief_per_day"),
    )
    
    def __repr__(self):
        return f"<AtlasDeskBrief(company_id={self.company_id}, desk='{self.desk_name}', signal='{self.signal_direction}')>"


class AtlasInstitutionalHolding(Base):
    """
    13F holdings from tracked hedge funds.
    Updated quarterly from SEC filings.
    """
    __tablename__ = "atlas_institutional_holdings"
    
    id = Column(Integer, primary_key=True)
    
    fund_name = Column(String(100), nullable=False, index=True)
    fund_cik = Column(String(10))
    
    # Position details
    ticker = Column(String(10), index=True)  # May be null if not in universe
    cusip = Column(String(9))
    company_name = Column(String(255))
    
    shares = Column(Float)  # Number of shares
    value = Column(Float)  # Value in USD (from 13F, in thousands * 1000)
    
    # Quarter info
    quarter = Column(String(7), nullable=False, index=True)  # e.g., "2026Q1"
    filing_date = Column(Date)
    
    # Change tracking
    change_type = Column(String(20))  # NEW, INCREASED, DECREASED, CLOSED, UNCHANGED
    change_pct = Column(Float)  # Percentage change from prior quarter
    portfolio_pct = Column(Float)  # Percentage of fund's portfolio
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index("ix_atlas_holdings_fund_quarter", "fund_name", "quarter"),
        Index("ix_atlas_holdings_ticker_quarter", "ticker", "quarter"),
        UniqueConstraint("fund_name", "cusip", "quarter", name="uq_holding_per_quarter"),
    )
    
    def __repr__(self):
        return f"<AtlasInstitutionalHolding(fund='{self.fund_name}', ticker='{self.ticker}', quarter='{self.quarter}')>"


class AtlasThesis(Base):
    """
    Investment theses generated by the CIO agent.
    A thesis is a structured investment case for a position.
    """
    __tablename__ = "atlas_theses"
    
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("atlas_companies.id"), nullable=False, index=True)
    
    # Thesis details
    direction = Column(String(10), nullable=False)  # LONG or SHORT
    confidence = Column(Float)  # 0.0 to 1.0
    
    # Investment case
    bull_case = Column(Text)
    bear_case = Column(Text)
    catalyst = Column(Text)  # What will unlock value
    timeframe = Column(String(50))  # e.g., "3-6 months"
    
    # Risk management
    invalidation_criteria = Column(Text)  # When to exit
    stop_loss_pct = Column(Float)
    target_return_pct = Column(Float)
    max_position_size_pct = Column(Float)
    
    # Status
    status = Column(String(20), default="ACTIVE", index=True)  # ACTIVE, INVALIDATED, CLOSED_WIN, CLOSED_LOSS
    status_reason = Column(Text)
    
    # Source briefs that informed this thesis
    source_brief_ids = Column(JSON)  # List of AtlasDeskBrief IDs
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    closed_at = Column(DateTime)
    
    # Relationships
    company = relationship("AtlasCompany", back_populates="theses")
    trades = relationship("AtlasTrade", back_populates="thesis")
    
    __table_args__ = (
        Index("ix_atlas_theses_status_date", "status", "created_at"),
    )
    
    def __repr__(self):
        return f"<AtlasThesis(company_id={self.company_id}, direction='{self.direction}', status='{self.status}')>"


class AtlasTrade(Base):
    """
    Paper trades executed based on theses.
    Tracks entry, exit, and P&L.
    """
    __tablename__ = "atlas_trades"
    
    id = Column(Integer, primary_key=True)
    thesis_id = Column(Integer, ForeignKey("atlas_theses.id"), nullable=False, index=True)
    
    ticker = Column(String(10), nullable=False, index=True)
    direction = Column(String(10), nullable=False)  # LONG or SHORT
    
    # Position sizing
    shares = Column(Float, nullable=False)
    
    # Entry
    entry_price = Column(Float, nullable=False)
    entry_date = Column(DateTime, nullable=False, index=True)
    entry_rationale = Column(Text)
    
    # Exit (null if position still open)
    exit_price = Column(Float)
    exit_date = Column(DateTime)
    exit_rationale = Column(Text)
    
    # P&L (calculated on exit)
    pnl_dollars = Column(Float)
    pnl_pct = Column(Float)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    thesis = relationship("AtlasThesis", back_populates="trades")
    
    __table_args__ = (
        Index("ix_atlas_trades_ticker_date", "ticker", "entry_date"),
    )
    
    def __repr__(self):
        return f"<AtlasTrade(ticker='{self.ticker}', direction='{self.direction}', entry='{self.entry_date}')>"


class AtlasPortfolioSnapshot(Base):
    """
    Daily portfolio snapshots for tracking performance.
    One row per day with full portfolio state.
    """
    __tablename__ = "atlas_portfolio_snapshots"
    
    id = Column(Integer, primary_key=True)
    
    date = Column(Date, unique=True, nullable=False, index=True)
    
    # Portfolio value
    total_value = Column(Float, nullable=False)  # Total portfolio value
    cash = Column(Float, nullable=False)  # Cash balance
    long_exposure = Column(Float)  # Total long value
    short_exposure = Column(Float)  # Total short value (absolute)
    net_exposure = Column(Float)  # Long - Short
    gross_exposure = Column(Float)  # Long + Short
    
    # Positions detail
    positions_json = Column(JSON)  # Full position details
    num_positions = Column(Integer)
    
    # Returns
    daily_return = Column(Float)  # Daily return percentage
    cumulative_return = Column(Float)  # Since inception
    
    # Risk metrics
    max_drawdown = Column(Float)  # Maximum drawdown to date
    sharpe_ratio = Column(Float)  # Rolling Sharpe
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<AtlasPortfolioSnapshot(date='{self.date}', value={self.total_value:,.0f}, return={self.daily_return:.2%})>"


# Indices for common queries
Index("ix_atlas_companies_sector_universe", AtlasCompany.sector, AtlasCompany.in_universe)
Index("ix_atlas_briefs_signal_confidence", AtlasDeskBrief.signal_direction, AtlasDeskBrief.confidence)
